# Generated by Django 3.2.13 on 2022-11-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрику',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('annotation', models.TextField(verbose_name='Аннотация')),
                ('image', models.ImageField(blank=True, default='images/empty.jpg', null=True, upload_to='images/', verbose_name='Изображение')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.rubric')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
