# Generated by Django 3.2.13 on 2022-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='articles',
            field=models.ManyToManyField(to='news.Article'),
        ),
    ]
